baseurl: http://converge.aster.is/
languageCode: en-us
title: Converge
theme: hugo-material-docs
metadataformat: yaml
canonifyurls: true

# Enable Google Analytics by entering your tracking id
googleAnalytics: ""

params:
  # General information
  author: Converge
  description: "TODO: punchy description"
  copyright: Released under the Apache 2.0 license

  # Repository
  provider: GitHub
  repo_url: https://github.com/asteris-llc/converge

  version: 0.3.0
  logo: images/logo.png
  favicon: ""

  permalink: '#'

  # Custom assets
  custom_css: []
  custom_js: []

  # Syntax highlighting themed
  highlight_css: ""

  palette:
    accent: light-green
    primary: red

  font:
    code: Ubuntu Mono
    text: Ubuntu

social:
  twitter: "asteris_llc"
  github: asteris-llc

menus:
  - main:

blackfriday:
  smartypants: true
  fractions: true
  smartDashes: true
  plainIDAnchors: true
